all:
	g++ `pkg-config --cflags --libs opencv` -o ColorizeLive ColorizeLive.cpp
	
#HERE TO REMIND ME of how to do it.. -I/usr/lib/jvm/java-6-sun-1.6.0.15/include -I/usr/lib/jvm/java-6-sun-1.6.0.15/include/linux -lCameraLib 
